// Canonical command registry. ADD commands here; do NOT scatter command
// definitions across files. Generators and the CLI both read this list.
//
// Phase 1 only `manifest` is `active`. Later phases promote `planned` → `active`.

import type { CommandSpec, Registry } from './types.js';

export const registry: Registry = {
  cliName: 'bunny-tools',
  binary: 'bunny',
  version: '0.1.0-rc.41',
  description: 'Bunny.net CLI — storage deploy, CDN purge, full resource management.',
  groups: [
    { name: 'configure', description: 'Manage credential profiles (set/list/switch/remove).' },
    { name: 'storage', description: 'File operations within a storage zone (upload/download/list/delete/sync).' },
    { name: 'storagezone', description: 'Manage storage zones (CRUD).' },
    { name: 'pullzone', description: 'Manage pull zones (CDN) and their edge rules.', aliases: ['cdn'] },
    { name: 'pullzone edgerule', description: 'Manage edge rules on a pull zone.' },
    { name: 'pullzone hostname', description: 'Manage custom hostnames linked to a pull zone.' },
    { name: 'domain', description: 'High-level domain operations (atomic Connect Domain flow).' },
    { name: 'dns', description: 'Manage DNS zones and records.' },
    { name: 'dns record', description: 'Manage DNS records within a zone.' },
    { name: 'stream', description: 'Manage Stream video libraries and videos.' },
    { name: 'stream library', description: 'Manage Stream video libraries.' },
    { name: 'stream video', description: 'Manage videos within a Stream library.' },
    { name: 'containers', description: 'Manage Magic Containers apps.' },
    { name: 'containers app', description: 'Manage Magic Containers application instances.' },
    { name: 'scripting', description: 'Manage Edge Scripting deployments.' },
    { name: 'install', description: 'One-shot bootstrap helpers (MCP config, CI scaffolds, ...).' },
  ],
  commands: [
    // Phase 1
    {
      name: 'manifest',
      summary: 'Print the bunny-tools command registry as JSON.',
      description:
        'Outputs the canonical command registry. AI agents and tooling read this to discover commands without parsing prose. Use --pretty for indented output.',
      flags: [
        {
          name: 'pretty',
          description: 'Indent the JSON output for readability.',
          hasValue: false,
          defaultValue: false,
        },
        {
          name: 'names',
          description: 'Emit one active command name per line (rc.10).',
          hasValue: false,
          defaultValue: false,
        },
      ],
      examples: [
        { command: 'bunny manifest', description: 'Compact JSON to stdout.' },
        { command: 'bunny manifest --pretty', description: 'Pretty-printed JSON.' },
        { command: 'bunny manifest --names', description: 'One command name per line.' },
      ],
      mcp: { tool: 'bunny.manifest', description: 'Returns the full bunny-tools registry as JSON.' },
      status: 'active',
      phase: 1,
      load: () => import('../commands/manifest.js'),
    },

    // Phase 2 — daily-use deploy loop
    {
      name: 'init',
      summary: 'Initialize a bunny.json + creds in one shot. Auth → feature multi-select → per-feature config.',
      args: [{ name: 'dir', description: 'Optional target directory (defaults to cwd).', required: false }],
      flags: [
        { name: 'non-interactive', description: 'Skip prompts and accept all values via flags.', hasValue: false },
        { name: 'force', description: 'Overwrite existing bunny.json.', hasValue: false },
        { name: 'account-key', description: 'Bunny account API key (skipped if env/keychain has one).', hasValue: true },
        { name: 'features', description: 'Comma-separated: storage,dns,stream,containers,scripting (or "all").', hasValue: true },
        { name: 'public-dir', description: 'Public directory to deploy (default: auto-detect).', hasValue: true },
        { name: 'storage-zone', description: 'Storage zone name (required for `storage` feature in non-interactive).', hasValue: true },
        { name: 'storage-password', description: 'Storage zone password (stored in keychain).', hasValue: true },
        { name: 'region', description: 'Override region (ny|la|sg|syd|uk|se|br|jh).', hasValue: true },
        { name: 'pull-zone', description: 'Pull zone id for CDN purge.', hasValue: true },
        { name: 'purge', description: 'Purge strategy: all|none|tag:<name>.', hasValue: true },
        { name: 'stream-library', description: 'Stream library id (when `stream` feature selected).', hasValue: true },
        { name: 'stream-key', description: 'Stream library API key.', hasValue: true },
        { name: 'ci', description: 'Generate .github/workflows/bunny-deploy.yml after init (GitHub Actions).', hasValue: false },
      ],
      examples: [
        { command: 'bunny init', description: 'Interactive wizard with feature multi-select.' },
        {
          command: 'bunny init --non-interactive --features=storage --account-key=$KEY --storage-zone=my-app --storage-password=$PW --pull-zone=12345',
          description: 'CI-friendly Storage+CDN setup.',
        },
        { command: 'bunny init --features=all --non-interactive ...', description: 'Enable every feature.' },
      ],
      mcp: { tool: 'bunny.init', description: 'Initialize a bunny.json (and creds if not set). Non-interactive shape.' },
      status: 'active',
      phase: 2,
      load: () => import('../commands/init.js'),
    },
    {
      name: 'configure',
      summary: 'Interactive credential walkthrough for a profile (account key + optional storage/stream).',
      flags: [
        { name: 'non-interactive', description: 'Skip prompts; accept all values via flags.', hasValue: false },
        { name: 'profile', description: 'Profile name (default: active profile, or "default").', hasValue: true },
        { name: 'account-key', description: 'Bunny account API key.', hasValue: true },
        { name: 'storage-zone', description: 'Default storage zone for this profile.', hasValue: true },
        { name: 'storage-password', description: 'Storage zone password.', hasValue: true },
        { name: 'pull-zone', description: 'Default pull zone id.', hasValue: true },
        { name: 'stream-library', description: 'Stream library id.', hasValue: true },
        { name: 'stream-key', description: 'Stream library API key.', hasValue: true },
      ],
      examples: [
        { command: 'bunny configure', description: 'Walkthrough for the active profile.' },
        { command: 'bunny configure --profile=work', description: 'Set up the "work" profile.' },
        {
          command: 'bunny configure --non-interactive --profile=ci --account-key=$KEY --storage-zone=my-app --storage-password=$PW',
          description: 'CI form.',
        },
      ],
      status: 'active',
      phase: 2,
      load: () => import('../commands/configure.js'),
    },
    {
      name: 'configure list',
      summary: 'List all credential profiles + stored scopes (masked). Active profile marked with *.',
      flags: [{ name: 'json', description: 'Emit JSON instead of a table.', hasValue: false }],
      status: 'active',
      phase: 2,
      load: () => import('../commands/configure/list.js'),
    },
    {
      name: 'configure switch',
      summary: 'Set the active credential profile.',
      args: [{ name: 'profile', description: 'Profile name to activate.', required: true }],
      status: 'active',
      phase: 2,
      load: () => import('../commands/configure/switch.js'),
    },
    {
      name: 'configure remove',
      summary: 'Remove a credential profile (entire) or a single scope within it.',
      flags: [
        { name: 'profile', description: 'Profile to remove (default: active).', hasValue: true },
        { name: 'scope', description: 'Remove only this scope (e.g. storage:my-app); else removes whole profile.', hasValue: true },
        { name: 'yes', description: 'Skip confirmation.', hasValue: false },
      ],
      status: 'active',
      phase: 2,
      load: () => import('../commands/configure/remove.js'),
    },
    {
      name: 'use',
      summary: 'Switch active alias from .bunnyrc; with no arg, list aliases.',
      args: [{ name: 'alias', description: 'Alias name (omit to list).', required: false }],
      flags: [
        { name: 'list', description: 'List aliases (default when no arg given).', hasValue: false },
        { name: 'json', description: 'Emit JSON instead of a table.', hasValue: false },
      ],
      status: 'active',
      phase: 2,
      load: () => import('../commands/use.js'),
    },
    {
      name: 'deploy',
      summary: 'Sync public dir to storage zone and purge CDN cache.',
      flags: [
        { name: 'dry-run', description: 'Plan and report without mutating remote.', hasValue: false },
        { name: 'delete', description: 'Delete orphan files on the remote.', hasValue: false },
        { name: 'concurrency', description: 'Parallel upload pool size.', hasValue: true, defaultValue: '8' },
        { name: 'purge', description: 'Override per-pull-zone purge: all|none|tag:<name>|paths.', hasValue: true },
        { name: 'only', description: 'Limit to a target (alias-scoped).', hasValue: true },
        { name: 'json', description: 'Emit JSON summary instead of a table.', hasValue: false },
        { name: 'verbose', description: 'Print Content-Type + size per file and full orphan list.', hasValue: false },
      ],
      examples: [
        { command: 'bunny deploy', description: 'Sync + purge per bunny.json.' },
        { command: 'bunny deploy --dry-run', description: 'Preview only.' },
        { command: 'bunny deploy --delete --concurrency=16', description: 'Aggressive sync.' },
      ],
      mcp: { tool: 'bunny.deploy' },
      status: 'active',
      phase: 2,
      load: () => import('../commands/deploy.js'),
    },
    {
      name: 'purge',
      summary: 'Purge CDN cache by URL or pullzone:<id>.',
      args: [{ name: 'target', description: '<url> | pullzone:<id>', required: true }],
      examples: [
        { command: 'bunny purge https://cdn.example.com/asset.js', description: 'Purge a specific URL.' },
        { command: 'bunny purge pullzone:12345', description: 'Full pull-zone purge.' },
      ],
      mcp: { tool: 'bunny.purge' },
      status: 'active',
      phase: 2,
      load: () => import('../commands/purge.js'),
    },

    // Phase 3 — storage + zones
    {
      name: 'storage upload',
      summary: 'Upload a file to a storage zone.',
      args: [
        { name: 'local', description: 'Local file path.', required: true },
        { name: 'remote', description: 'Remote path within the zone.', required: true },
      ],
      flags: [
        { name: 'zone', description: 'Storage zone name.', hasValue: true },
        { name: 'region', description: 'Override region (e.g. ny, la).', hasValue: true },
      ],
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage/upload.js'),
    },
    {
      name: 'storage download',
      summary: 'Download a file from a storage zone.',
      args: [
        { name: 'remote', description: 'Remote path within the zone.', required: true },
        { name: 'local', description: 'Local destination path.', required: true },
      ],
      flags: [
        { name: 'zone', description: 'Storage zone name.', hasValue: true },
        { name: 'region', description: 'Override region.', hasValue: true },
      ],
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage/download.js'),
    },
    {
      name: 'storage list',
      summary: 'List a storage-zone path.',
      args: [{ name: 'path', description: 'Path within the zone (default /).', required: false }],
      flags: [
        { name: 'zone', description: 'Storage zone name.', hasValue: true },
        { name: 'recursive', description: 'List recursively.', hasValue: false },
        { name: 'json', description: 'Emit JSON.', hasValue: false },
        { name: 'region', description: 'Override region.', hasValue: true },
      ],
      mcp: { tool: 'bunny.storage_list' },
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage/list.js'),
    },
    {
      name: 'storage delete',
      summary: 'Delete a file or path from a storage zone.',
      args: [{ name: 'path', description: 'Remote path.', required: true }],
      flags: [
        { name: 'zone', description: 'Storage zone name.', hasValue: true },
        { name: 'recursive', description: 'Delete recursively.', hasValue: false },
        { name: 'yes', description: 'Skip confirmation.', hasValue: false },
        { name: 'region', description: 'Override region.', hasValue: true },
      ],
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage/delete.js'),
    },
    {
      name: 'storage sync',
      summary: 'Sync a local directory to a storage zone (upload-only, no purge).',
      args: [
        { name: 'local', description: 'Local directory.', required: true },
        { name: 'remote', description: 'Remote root path (default /).', required: false },
      ],
      flags: [
        { name: 'zone', description: 'Storage zone name.', hasValue: true },
        { name: 'concurrency', description: 'Parallel pool size.', hasValue: true, defaultValue: '8' },
        { name: 'region', description: 'Override region.', hasValue: true },
      ],
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage/sync.js'),
    },
    {
      name: 'storagezone list',
      summary: 'List storage zones.',
      flags: [{ name: 'json', description: 'Emit JSON.', hasValue: false }],
      mcp: { tool: 'bunny.zones_list' },
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage-zone/list.js'),
    },
    {
      name: 'storagezone get',
      summary: 'Get a storage zone by id or name.',
      args: [{ name: 'idOrName', description: 'Numeric id or zone name.', required: true }],
      mcp: { tool: 'bunny.zone_get' },
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage-zone/get.js'),
    },
    {
      name: 'storagezone create',
      summary: 'Create a storage zone.',
      args: [{ name: 'name', description: 'Zone name.', required: true }],
      flags: [
        { name: 'region', description: 'Primary region (e.g. ny, la, sg).', hasValue: true },
        { name: 'replicate', description: 'Comma-separated replication regions.', hasValue: true },
        { name: 'tier', description: 'Standard | Edge.', hasValue: true },
      ],
      mcp: { tool: 'bunny.zone_create' },
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage-zone/create.js'),
    },
    {
      name: 'storagezone update',
      summary: 'Update a storage zone (raw JSON body).',
      args: [{ name: 'id', description: 'Storage zone id.', required: true }],
      flags: [{ name: 'body', description: 'JSON body to POST.', hasValue: true }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage-zone/update.js'),
    },
    {
      name: 'storagezone delete',
      summary: 'Delete a storage zone.',
      args: [{ name: 'id', description: 'Storage zone id.', required: true }],
      flags: [{ name: 'yes', description: 'Skip confirmation.', hasValue: false }],
      mcp: { tool: 'bunny.zone_delete' },
      status: 'active',
      phase: 3,
      load: () => import('../commands/storage-zone/delete.js'),
    },
    {
      name: 'pullzone list',
      summary: 'List pull zones.',
      flags: [{ name: 'json', description: 'Emit JSON.', hasValue: false }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/list.js'),
    },
    {
      name: 'pullzone get',
      summary: 'Get a pull zone.',
      args: [{ name: 'id', description: 'Pull zone id.', required: true }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/get.js'),
    },
    {
      name: 'pullzone create',
      summary: 'Create a pull zone.',
      args: [{ name: 'name', description: 'Pull zone name.', required: true }],
      flags: [{ name: 'origin', description: 'Origin URL.', hasValue: true }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/create.js'),
    },
    {
      name: 'pullzone update',
      summary: 'Update a pull zone (raw JSON body).',
      args: [{ name: 'id', description: 'Pull zone id.', required: true }],
      flags: [{ name: 'body', description: 'JSON body to POST.', hasValue: true }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/update.js'),
    },
    {
      name: 'pullzone delete',
      summary: 'Delete a pull zone.',
      args: [{ name: 'id', description: 'Pull zone id.', required: true }],
      flags: [{ name: 'yes', description: 'Skip confirmation.', hasValue: false }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/delete.js'),
    },
    {
      name: 'pullzone edgerule list',
      summary: 'List edge rules on a pull zone.',
      args: [{ name: 'pullZoneId', description: 'Pull zone id.', required: true }],
      flags: [{ name: 'json', description: 'Emit JSON.', hasValue: false }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/edge-rule/list.js'),
    },
    {
      name: 'pullzone edgerule add',
      summary: 'Add an edge rule to a pull zone (raw JSON rule).',
      args: [{ name: 'pullZoneId', description: 'Pull zone id.', required: true }],
      flags: [{ name: 'rule', description: 'JSON rule body.', hasValue: true }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/edge-rule/add.js'),
    },
    {
      name: 'pullzone edgerule delete',
      summary: 'Delete an edge rule by Guid.',
      args: [
        { name: 'pullZoneId', description: 'Pull zone id.', required: true },
        { name: 'ruleGuid', description: 'Edge rule Guid.', required: true },
      ],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/edge-rule/delete.js'),
    },
    {
      name: 'pullzone hostname list',
      summary: 'List custom hostnames linked to a pull zone.',
      args: [{ name: 'pullZoneId', description: 'Pull zone id.', required: true }],
      flags: [{ name: 'json', description: 'Emit JSON.', hasValue: false }],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/hostname/list.js'),
    },
    {
      name: 'pullzone hostname add',
      summary:
        'Idempotent: link hostname + provision Let\'s Encrypt cert + enable ForceSSL (HTTP→HTTPS). Pass --no-force-ssl to provision cert without the HTTP→HTTPS redirect.',
      args: [
        { name: 'pullZoneId', description: 'Pull zone id.', required: true },
        { name: 'hostname', description: 'Custom hostname (e.g. example.com).', required: true },
      ],
      flags: [
        { name: 'no-force-ssl', description: 'Provision cert but disable HTTP→HTTPS redirect (state assertion: re-run flips OFF).', hasValue: false },
        { name: 'timeout', description: 'Cert wait timeout in seconds (default 90).', hasValue: true, defaultValue: '90' },
      ],
      examples: [
        { command: 'bunny pullzone hostname add 555 example.com', description: 'Link + cert + ForceSSL on (default-secure).' },
        { command: 'bunny pullzone hostname add 555 legacy.example.com --no-force-ssl', description: 'Link + cert, but allow plain HTTP for legacy clients.' },
      ],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/hostname/add.js'),
    },
    {
      name: 'pullzone hostname remove',
      summary: 'Unlink a custom hostname from a pull zone.',
      args: [
        { name: 'pullZoneId', description: 'Pull zone id.', required: true },
        { name: 'hostname', description: 'Custom hostname.', required: true },
      ],
      status: 'active',
      phase: 3,
      load: () => import('../commands/pull-zone/hostname/remove.js'),
    },

    {
      name: 'domain connect',
      summary:
        'Atomic Connect Domain: link hostname to PZ, provision Let\'s Encrypt cert, optionally create the apex Type-7 DNS record. Idempotent — safe to re-run.',
      args: [
        { name: 'pullZoneId', description: 'Pull zone id.', required: true },
        { name: 'hostname', description: 'FQDN to connect (e.g. example.com).', required: true },
      ],
      flags: [
        { name: 'dns-zone', description: 'Also create the Type-7 PULLZONE DNS record in this DNS zone id.', hasValue: true },
        { name: 'name', description: 'DNS record name when --dns-zone is given. Empty/`@` for apex (default).', hasValue: true },
        { name: 'no-wait', description: 'Skip cert provisioning poll (advanced; caller verifies separately).', hasValue: false },
        { name: 'timeout', description: 'Cert wait timeout in seconds (default 90).', hasValue: true, defaultValue: '90' },
        { name: 'no-force-ssl', description: 'Skip auto-enabling ForceSSL (HTTP→HTTPS redirect).', hasValue: false },
      ],
      examples: [
        { command: 'bunny domain connect 5789465 example.com', description: 'Link hostname + provision cert. Add DNS record separately.' },
        { command: 'bunny domain connect 5789465 example.com --dns-zone=784669', description: 'End-to-end: hostname + cert + apex Type-7 record.' },
      ],
      status: 'active',
      phase: 3,
      load: () => import('../commands/domain/connect.js'),
    },

    // Phase 4 — DNS
    {
      name: 'dns list',
      summary: 'List DNS zones.',
      flags: [{ name: 'json', description: 'Emit JSON.', hasValue: false }],
      status: 'active',
      phase: 4,
      load: () => import('../commands/dns/list.js'),
    },
    {
      name: 'dns get',
      summary: 'Get a DNS zone (with records) by id.',
      args: [{ name: 'id', description: 'DNS zone id.', required: true }],
      status: 'active',
      phase: 4,
      load: () => import('../commands/dns/get.js'),
    },
    {
      name: 'dns create',
      summary: 'Create a DNS zone for a domain.',
      args: [{ name: 'domain', description: 'Domain name.', required: true }],
      status: 'active',
      phase: 4,
      load: () => import('../commands/dns/create.js'),
    },
    {
      name: 'dns delete',
      summary: 'Delete a DNS zone.',
      args: [{ name: 'id', description: 'DNS zone id.', required: true }],
      flags: [{ name: 'yes', description: 'Skip confirmation.', hasValue: false }],
      status: 'active',
      phase: 4,
      load: () => import('../commands/dns/delete.js'),
    },
    {
      name: 'dns record list',
      summary: 'List DNS records for a zone.',
      args: [{ name: 'zoneId', description: 'DNS zone id.', required: true }],
      flags: [
        { name: 'type', description: 'Filter by record type.', hasValue: true },
        { name: 'json', description: 'Emit JSON.', hasValue: false },
      ],
      mcp: { tool: 'bunny.dns_records' },
      status: 'active',
      phase: 4,
      load: () => import('../commands/dns/record/list.js'),
    },
    {
      name: 'dns record add',
      summary:
        'Add a DNS record (A, AAAA, CNAME, TXT, MX, REDIRECT, PULLZONE, SRV, CAA, PTR, SCRIPT, NS).',
      args: [
        { name: 'zoneId', description: 'DNS zone id.', required: true },
        { name: 'type', description: 'Record type.', required: true },
        { name: 'name', description: 'Record name.', required: true },
        // Optional when --pull-zone is used; the convenience flag fills it
        // from the pull zone\'s registered Name.
        { name: 'value', description: 'Record value (optional with --pull-zone).', required: false },
      ],
      flags: [
        { name: 'ttl', description: 'TTL in seconds.', hasValue: true },
        { name: 'priority', description: 'Priority (MX/SRV).', hasValue: true },
        { name: 'weight', description: 'Weight (SRV).', hasValue: true },
        { name: 'port', description: 'Port (SRV).', hasValue: true },
        { name: 'flags', description: 'Flags (CAA).', hasValue: true },
        { name: 'tag', description: 'Tag (CAA).', hasValue: true },
        { name: 'link-name', description: 'Linked resource id as string (PULLZONE/SCRIPT).', hasValue: true },
        { name: 'pull-zone', description: 'Convenience for PULLZONE: numeric pz id; auto-fills value + link-name.', hasValue: true },
      ],
      mcp: { tool: 'bunny.dns_record_set' },
      status: 'active',
      phase: 4,
      load: () => import('../commands/dns/record/add.js'),
    },
    {
      name: 'dns record update',
      summary: 'Update a DNS record (raw JSON body).',
      args: [
        { name: 'zoneId', description: 'DNS zone id.', required: true },
        { name: 'recordId', description: 'Record id.', required: true },
      ],
      flags: [{ name: 'body', description: 'JSON body.', hasValue: true }],
      status: 'active',
      phase: 4,
      load: () => import('../commands/dns/record/update.js'),
    },
    {
      name: 'dns record delete',
      summary: 'Delete a DNS record.',
      args: [
        { name: 'zoneId', description: 'DNS zone id.', required: true },
        { name: 'recordId', description: 'Record id.', required: true },
      ],
      flags: [{ name: 'yes', description: 'Skip confirmation.', hasValue: false }],
      mcp: { tool: 'bunny.dns_record_delete' },
      status: 'active',
      phase: 4,
      load: () => import('../commands/dns/record/delete.js'),
    },

    // Phase 5 — Stream / Magic Containers / Edge Scripting
    {
      name: 'stream library list',
      summary: 'List Stream video libraries.',
      flags: [{ name: 'json', description: 'Emit JSON.', hasValue: false }],
      status: 'active',
      phase: 5,
      load: () => import('../commands/stream/library/list.js'),
    },
    {
      name: 'stream library create',
      summary: 'Create a Stream video library.',
      args: [{ name: 'name', description: 'Library name.', required: true }],
      flags: [{ name: 'replicate', description: 'Comma-separated replication regions.', hasValue: true }],
      status: 'active',
      phase: 5,
      load: () => import('../commands/stream/library/create.js'),
    },
    {
      name: 'stream library delete',
      summary: 'Delete a Stream video library.',
      args: [{ name: 'id', description: 'Library id.', required: true }],
      flags: [{ name: 'yes', description: 'Skip confirmation.', hasValue: false }],
      status: 'active',
      phase: 5,
      load: () => import('../commands/stream/library/delete.js'),
    },
    {
      name: 'stream video list',
      summary: 'List videos in a library.',
      args: [{ name: 'library', description: 'Video library id.', required: true }],
      flags: [
        { name: 'collection', description: 'Filter by collection id.', hasValue: true },
        { name: 'json', description: 'Emit JSON.', hasValue: false },
      ],
      status: 'active',
      phase: 5,
      load: () => import('../commands/stream/video/list.js'),
    },
    {
      name: 'stream video upload',
      summary: 'Upload a video to a library.',
      args: [
        { name: 'library', description: 'Video library id.', required: true },
        { name: 'file', description: 'Local video file path.', required: true },
      ],
      flags: [
        { name: 'title', description: 'Video title.', hasValue: true },
        { name: 'collection', description: 'Collection id.', hasValue: true },
      ],
      status: 'active',
      phase: 5,
      load: () => import('../commands/stream/video/upload.js'),
    },
    {
      name: 'stream video delete',
      summary: 'Delete a video.',
      args: [
        { name: 'library', description: 'Video library id.', required: true },
        { name: 'video', description: 'Video guid.', required: true },
      ],
      flags: [{ name: 'yes', description: 'Skip confirmation.', hasValue: false }],
      status: 'active',
      phase: 5,
      load: () => import('../commands/stream/video/delete.js'),
    },
    {
      name: 'containers app list',
      summary: 'List Magic Containers apps.',
      flags: [{ name: 'json', description: 'Emit JSON.', hasValue: false }],
      status: 'active',
      phase: 5,
      load: () => import('../commands/containers/app/list.js'),
    },
    {
      name: 'containers app create',
      summary: 'Create a Magic Containers app.',
      args: [{ name: 'name', description: 'App name.', required: true }],
      flags: [
        { name: 'image', description: 'Docker image (e.g. ghcr.io/x/y:tag).', hasValue: true },
        { name: 'region', description: 'Deploy region.', hasValue: true },
        { name: 'port', description: 'Container port.', hasValue: true },
      ],
      // Demoted in rc.12 — Bunny Containers v3 schema requires `runtimeType`,
      // `containerTemplates[]`, and `autoScaling.{min,max}`. Current body shape
      // produced HTTP 400 in live testing. Re-promote in v0.2 after a schema
      // rewrite. Existing list/delete commands stay active.
      status: 'planned',
      phase: 5,
    },
    {
      name: 'containers app delete',
      summary: 'Delete a Magic Containers app.',
      args: [{ name: 'id', description: 'App id.', required: true }],
      flags: [{ name: 'yes', description: 'Skip confirmation.', hasValue: false }],
      status: 'active',
      phase: 5,
      load: () => import('../commands/containers/app/delete.js'),
    },
    {
      name: 'scripting list',
      summary: 'List edge scripts.',
      flags: [{ name: 'json', description: 'Emit JSON.', hasValue: false }],
      status: 'active',
      phase: 5,
      load: () => import('../commands/scripting/list.js'),
    },
    {
      name: 'scripting deploy',
      summary: 'Deploy an edge script from a source file (creates new, or updates by id).',
      args: [{ name: 'name', description: 'Script name.', required: true }],
      flags: [
        { name: 'file', description: 'Local source file.', hasValue: true },
        { name: 'id', description: 'Existing script id (update mode).', hasValue: true },
        { name: 'type', description: 'Numeric script type.', hasValue: true },
      ],
      status: 'active',
      phase: 5,
      load: () => import('../commands/scripting/deploy.js'),
    },
    {
      name: 'scripting delete',
      summary: 'Delete an edge script.',
      args: [{ name: 'id', description: 'Script id.', required: true }],
      flags: [{ name: 'yes', description: 'Skip confirmation.', hasValue: false }],
      status: 'active',
      phase: 5,
      load: () => import('../commands/scripting/delete.js'),
    },

    // rc.19 — DX polish (install bootstrap + self-update)
    {
      name: 'install mcp',
      summary: 'Register bunny-tools as an MCP server in Claude Code (one-shot bootstrap).',
      flags: [
        { name: 'scope', description: 'MCP scope: user | project | local (default: user).', hasValue: true },
      ],
      examples: [
        { command: 'bunny install mcp', description: 'Add bunny-tools to Claude\'s user-scope MCP config.' },
        { command: 'bunny install mcp --scope=project', description: 'Add to the current project\'s .claude config.' },
      ],
      status: 'active',
      phase: 7,
      load: () => import('../commands/install/mcp.js'),
    },
    {
      name: 'update',
      summary: 'Self-update bunny-tools to the latest version on npm.',
      flags: [
        { name: 'yes', description: 'Skip confirmation prompt.', hasValue: false },
      ],
      examples: [
        { command: 'bunny update', description: 'npm install -g bunny-tools@latest.' },
      ],
      status: 'active',
      phase: 7,
      load: () => import('../commands/update.js'),
    },

    // Phase 6 — MCP server
    {
      name: 'mcp',
      summary: 'Boot the bunny-tools MCP stdio server (for AI agents).',
      flags: [
        { name: 'http', description: 'Enable HTTP/SSE transport (deferred to v0.2).', hasValue: false },
      ],
      examples: [
        {
          command: 'claude mcp add bunny-tools npx -y bunny-tools mcp',
          description: 'Install for Claude Code.',
        },
      ],
      status: 'active',
      phase: 6,
      load: () => import('../commands/mcp.js'),
    },

    // rc.8 — wrangler-inspired wins.
    {
      name: 'whoami',
      summary: 'Show the current account context (stored credentials + reachable zone counts).',
      flags: [{ name: 'json', description: 'Emit JSON instead of a table.', hasValue: false }],
      status: 'active',
      phase: 2,
      load: () => import('../commands/whoami.js'),
    },
    {
      name: 'docs',
      summary: 'Open Bunny.net docs in the browser. Optional [topic] for direct deep links.',
      args: [{ name: 'topic', description: 'Topic shortcut (e.g. storage, pullzone, dns) or path slug.', required: false }],
      examples: [
        { command: 'bunny docs', description: 'Opens docs.bunny.net root.' },
        { command: 'bunny docs storage', description: 'Storage introduction.' },
        { command: 'bunny docs pullzone', description: 'CDN pull zone reference.' },
      ],
      status: 'active',
      phase: 2,
      load: () => import('../commands/docs.js'),
    },
  ],
};

export function listMcpTools(): { name: string; tool: string; description?: string }[] {
  return registry.commands
    .filter((c) => c.mcp !== undefined)
    .map((c) => ({ name: c.name, tool: c.mcp!.tool, description: c.mcp!.description ?? c.summary }));
}

export function findCommand(name: string): CommandSpec | undefined {
  return registry.commands.find((c) => c.name === name);
}
