// CI workflow generator. v1 supports GitHub Actions only — ~80% of users
// per public repo data. GitLab/CircleCI templates can land in v0.2 once we
// have demand. Generated YAML is intentionally readable + editable; users
// will tweak it for their pipeline (test step, env-specific deploys, etc.).

import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import type { BunnyJson } from '../config/bunny-json.js';

export type CiWorkflowResult =
  | { wrote: true; path: string; secretsToAdd: string[] }
  | { wrote: false; reason: 'exists'; path: string; secretsToAdd: string[] };

const WORKFLOW_REL_PATH = '.github/workflows/bunny-deploy.yml';

export async function generateGitHubActionsWorkflow(
  cwd: string,
  config: BunnyJson,
): Promise<CiWorkflowResult> {
  const path = join(cwd, WORKFLOW_REL_PATH);
  const secrets = secretsToAdd(config);
  if (existsSync(path)) {
    return { wrote: false, reason: 'exists', path, secretsToAdd: secrets };
  }
  const yaml = renderGitHubActionsYaml(config);
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, yaml, 'utf8');
  return { wrote: true, path, secretsToAdd: secrets };
}

// Required secrets are per-zone (storage password) + global (account key).
// GitHub Actions normalizes secret names to UPPER_SNAKE_CASE; mirror the
// resolver chain's BUNNY_STORAGE_PASSWORD_<ZONE_UPPER> convention.
function secretsToAdd(config: BunnyJson): string[] {
  const out = ['BUNNY_ACCOUNT_KEY'];
  const zone = config.deploy.storageZone;
  if (zone) {
    const upper = zone.replaceAll('-', '_').toUpperCase();
    out.push(`BUNNY_STORAGE_PASSWORD_${upper}`);
  }
  return out;
}

function renderGitHubActionsYaml(config: BunnyJson): string {
  const zone = config.deploy.storageZone;
  const upper = zone ? zone.replaceAll('-', '_').toUpperCase() : 'YOUR_ZONE';
  const passwordSecret = `BUNNY_STORAGE_PASSWORD_${upper}`;
  // YAML output is hand-rolled (no js-yaml dep) — single-purpose template
  // with fixed structure, no need for a serializer. Indented by 2 spaces.
  return `# Generated by \`bunny init --ci\`. Edit freely.
name: Deploy to Bunny.net

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'plans/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install bunny-tools
        run: npm install -g bunny-tools
      - name: Deploy
        env:
          BUNNY_ACCOUNT_KEY: \${{ secrets.BUNNY_ACCOUNT_KEY }}
          ${passwordSecret}: \${{ secrets.${passwordSecret} }}
        run: bunny deploy --delete
`;
}
